<?php

namespace App\GeneralBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
    /**
     * Get projects for which user has permissions
     *
     * @param  integer $userId
     * @return array
     */
    public function getUserAvailableProjects($userId)
    {
        $dql = "
            SELECT
                ptt.id AS project_to_task_id,
                p.id AS project_id, p.name AS project_name,
                c.id AS company_id, c.name AS company_name,
                t.id AS task_id, t.name AS task_name
            FROM AppGeneralBundle:Project p
            JOIN p.tasks ptt
            JOIN ptt.task t
            JOIN p.users u WITH u = :userId
            JOIN p.company c
            ORDER BY c.name, p.name, t.name
        ";

        $query = $this->getEntityManager()->createQuery($dql);
        $query->setParameter('userId', $userId);

        return $query->getArrayResult();
    }
}
