<?php

namespace App\GeneralBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TimesheetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimesheetRepository extends EntityRepository
{
    public function getWeeklyTimesheet(\DateTime $date, $userId)
    {
        return array();
    }

    public function getDailyTimesheet(\DateTime $date, $userId)
    {
        return array();
    }
}
