<?php

namespace App\GeneralBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TimesheetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimesheetRepository extends EntityRepository
{
    /**
     * Get weekly timesheet for given user
     *
     * @param  integer $year
     * @param  integer $week
     * @param  integer $userId
     * @return array
     */
    public function getWeeklyTimesheet($year, $week, $userId)
    {
        $dql = "
            SELECT
                ptt.id AS id,
                ti.weekDay AS day,
                ti.workTime AS time,
                p.name AS project_name,
                task.name AS task_name,
                c.name AS company_name
            FROM AppGeneralBundle:Timesheet t
            JOIN t.timesheetItems ti
            JOIN t.task ptt
            JOIN ptt.project p
            JOIN ptt.task task
            JOIN p.company c
            WHERE t.user = :userId
            AND t.year = :year
            AND t.week = :week
            ORDER BY t.created ASC
        ";
        $query = $this->getEntityManager()->createQuery($dql);
        $query->setParameter("userId", $userId);
        $query->setParameter("year", $year);
        $query->setParameter("week", $week);

        return $query->getArrayResult();
    }

    public function getDailyTimesheet(\DateTime $date, $userId)
    {
        return array();
    }
}
