timesheet_week:
    pattern:  /show/{year}/{month}/{day}
    defaults: { _controller: AppFrontendBundle:TimesheetWeek:index, year: "", month: "", day: "" }

timesheet_week_new_task:
    pattern:  /new/task/{year}/{week}
    defaults: { _controller: AppFrontendBundle:TimesheetWeek:newTask}
    options:
        expose: true

timesheet_week_create_task:
    pattern:  /create/task/{year}/{week}
    defaults: { _controller: AppFrontendBundle:TimesheetWeek:createTask}
    requirements:
        _method:  POST
    options:
        expose: true
