#definition of all sonata admin controllers
services:

    # user list
    app_backend.admin.user_admin:
        class: App\BackendBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Users, label: User list }
        arguments: [null, App\GeneralBundle\Entity\User, AppBackendBundle:UserAdmin]
        calls:
            - [ setTranslationDomain, ["user"] ]
            - [ setUserManager, [@fos_user.user_manager] ]
            - [ setSecurityContent, [@security.context] ]
            - [ setMailer, [@app_general.services.mailer] ]
            - [ setTwig, [@twig] ]

    # company list
    app_backend.admin.company_admin:
        class: App\BackendBundle\Admin\CompanyAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Manage, label: Clients }
        arguments: [null, App\GeneralBundle\Entity\Company, AppBackendBundle:CompanyAdmin]
        calls:
            - [ setTranslationDomain, ["backend_company"] ]

    # project list
    app_backend.admin.project_admin:
        class: App\BackendBundle\Admin\ProjectAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Manage, label: Projects }
        arguments: [null, App\GeneralBundle\Entity\Project, AppBackendBundle:ProjectAdmin]
        calls:
            - [ setTranslationDomain, ["backend_project"] ]

    # task list
    app_backend.admin.task_admin:
        class: App\BackendBundle\Admin\TaskAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Manage, label: Tasks }
        arguments: [null, App\GeneralBundle\Entity\Task, AppBackendBundle:TaskAdmin]
        calls:
            - [ setTranslationDomain, ["backend_task"] ]

    # timesheet list
    app_backend.admin.timesheet_admin:
        class: App\BackendBundle\Admin\TimesheetAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Reports, label: Timesheet }
        arguments: [null, App\GeneralBundle\Entity\Timesheet, AppBackendBundle:TimesheetAdmin]
        calls:
            - [ setTranslationDomain, ["backend_timesheet"] ]